app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}
server.port=${SERVER_PORT:8080}
server.forward-headers-strategy=framework

# Below settings, allows Docker to expose the port to the host machine
server.address=0.0.0.0

##### Logging Level #####
logging.level.root=DEBUG
logging.level.org.springdoc=DEBUG
logging.level.org.springframework=DEBUG

# Logging configuration for Spring Web
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.boot.autoconfigure=DEBUG

logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
logging.level.com.zaxxer.hikari=TRACE