server {
    listen 80;
    listen [::]:80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    #--------------------------------------------------
    # GZIP compression
    #--------------------------------------------------
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 5;
	gzip_min_length 1024;
    gzip_types
        text/plain
        text/css
        text/xml
        application/json
        application/javascript
        application/xml
        application/rss+xml
        image/svg+xml;
    
    #--------------------------------------------------
    # Hashed frontend assets: cache for a long time
    #--------------------------------------------------
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }
    
    #--------------------------------------------------
    # React SPA fallback: always serve index.html (never cache it)
    #--------------------------------------------------
    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store";
    }
    
    #--------------------------------------------------
    # This should only be used when you are working with static website
    #--------------------------------------------------
    #location / {
    #       try_files $uri $uri/ =404;
    #}
    
    #--------------------------------------------------
    # Backend API
    # /app/api/v1/status
    #       ↓
    # backend:8080/app/api/v1/status
    #--------------------------------------------------
    location /app/ {
        proxy_pass http://backend:8080;

        proxy_http_version 1.1;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;

        # Keep these if backend uses WebSockets
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    
    #--------------------------------------------------
    # Security headers
    #--------------------------------------------------
    #add_header X-Frame-Options "DENY" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    #add_header X-XSS-Protection "1; mode=block";
	#add_header Referrer-Policy "no-referrer" always;
	#add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; font-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none';" always;
	#add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
}